# Part 1: Training and evaluating simple CNNs

__Before starting, we recommend you enable GPU acceleration if you're running on Colab.__

In [2]:
# Execute this code block to install dependencies when running on colab
try:
    import torch
except:
    from os.path import exists
    from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
    platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
    cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
    accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

    !pip install -q http://download.pytorch.org/whl/{accelerator}/torch-1.0.0-{platform}-linux_x86_64.whl torchvision

try: 
    import torchbearer
except:
    !pip install torchbearer

## Simple Convolutional Neural Network for MNIST

Now that we have seen how to load the MNIST dataset and train a simple multi-layer perceptron model on it, we can now start to develop a more sophisticated convolutional neural network or CNN model. PyTorch provides a lot of capability for creating CNNs, and includes a large number of layer types and activation functions. In this part of the lab we will create a simple CNN for MNIST that demonstrates how to use all of the aspects of a modern CNN implementation, including Convolutional layers, Pooling layers and Dropout layers.

The first step is to import the classes and functions needed.

In [3]:
# automatically reload external modules if they change
%load_ext autoreload
%autoreload 2

import torch
import torch.nn.functional as F
import torchvision.transforms as transforms
import torchbearer
from torch import nn
from torch import optim
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchbearer import Trial

Again, initialise the random number generator to a constant seed value for reproducibility of results.

In [4]:
# fix random seed for reproducibility
seed = 7
torch.manual_seed(seed)
torch.backends.cudnn.deterministic = True

Next we need to load the MNIST dataset. Unlike with the MLP example we looked at previously, we don't want to flatten the images into vectors, although we do still want to convert the PIL images to tensors.

In PyTorch, images are represented as tensors with dimensions `[pixels][height][width]`. In the case of RGB, the first dimension, pixels, would be 3 for the red, green and blue components. In the case of MNIST where the pixel values are greyscale, the pixel dimension is set to 1.

In [4]:
# convert each image to tensor format
transform = transforms.Compose([
    transforms.ToTensor()  # convert to tensor
])

# load data
trainset = MNIST(".", train=True, download=True, transform=transform)
testset = MNIST(".", train=False, download=True, transform=transform)

# create data loaders
trainloader = DataLoader(trainset, batch_size=128, shuffle=True)
testloader = DataLoader(testset, batch_size=128, shuffle=True)

Next we define our neural network model.

Convolutional neural networks are more complex than standard multi-layer perceptrons, so we will start by using a simple structure to begin with that uses all of the elements required for near state of the art results. The network architecture is summarised below:

1. The first hidden layer is a convolutional layer called a `Convolution2D`. The layer has 32 feature maps, which with the size of 5×5 and a rectified linear unit activation function.
2. Next we define a pooling layer that takes the max called `MaxPooling2D`. It is configured with a pool size of 2×2.
3. The next layer is a regularization layer using dropout called `Dropout`. It is configured to randomly exclude 20% of neurons in the layer in order to reduce overfitting.
4. Next is an operation that flattens or reshapes the tensor to a vector. It allows the output to be processed by standard fully connected layers.
5. Next a fully connected layer with 128 neurons and rectifier linear unit activation function.
6. Finally, the output layer has 10 neurons for the 10 classes.

Just like with the MLP we create a PyTorch `nn.Module` subclass to define our network model:

In [5]:
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, (5, 5), padding=0)
        self.fc1 = nn.Linear(32 * 12**2, 128)
        self.fc2 = nn.Linear(128, 10)
            
    def forward(self, x):
        out = self.conv1(x)
        out = F.relu(out)
        out = F.max_pool2d(out, (2,2))
        out = F.dropout(out, 0.2)
        out = out.view(out.shape[0], -1)
        out = self.fc1(out)
        out = F.relu(out)
        out = self.fc2(out)
        return out

Note in the above code when we use the `view` method to _flatten_ the tensor we must preserve the batch dimension of the data; passing `-1` as the second argument tells view to compute the size of the dimension represented by the `-1` automatically. The input to the forward method has shape `[batch_size][pixels][height][width]` and we want the final output to be `[batch_size][num_classes=10]`. 

__Answer the following questions (enter the answer in the box below each one):__

__1.__ What is the shape of the tensor output by the `conv1` layer?

(32-5)+1 = 28

28\*28\*32

__2.__ If the `conv1` layer had a kernel shape of `(7,3)` what would the output shape be?

YOUR ANSWER HERE

As before, the model is trained using cross-entropy loss and the ADAM gradient descent algorithm. The CNN is fit over 10 epochs with a batch size of 128. We use torchbearer to minimise the training and evaluation code we need to write:

In [6]:
# build the model
model = SimpleCNN()

# define the loss function and the optimiser
loss_function = nn.CrossEntropyLoss()
optimiser = optim.Adam(model.parameters())

device = "cuda:0" if torch.cuda.is_available() else "cpu"
trial = Trial(model, optimiser, loss_function, metrics=['loss', 'accuracy']).to(device)
trial.with_generators(trainloader, test_generator=testloader)
trial.run(epochs=10)
results = trial.evaluate(data_key=torchbearer.TEST_DATA)
print(results)


{'test_loss': 0.038808271288871765, 'test_acc': 0.9884999990463257}


You should see that the network achieves an accuracy of 98.91% which is better than the simple multi-layer perceptron model we tried previously.

## An improved CNN

Now that we have seen how to create a simple CNN, let’s take a look at a model capable of close to state of the art results. This time you will implement a large CNN architecture with additional convolutional, max pooling layers and fully connected layers. The network topology of the model is summarised as follows:

1. Convolutional layer with 30 feature maps of size 5×5 and ReLU activation.
2. Pooling layer taking the max over 2×2 patches.
3. Convolutional layer with 15 feature maps of size 3×3 and ReLU activation.
4. Pooling layer taking the max over 2×2 patches.
5. Dropout layer with a probability of 20%.
6. Flatten layer.
7. Fully connected layer with 128 neurons and ReLU activation.
8. Fully connected layer with 50 neurons and ReLU activation.
9. Linear output layer.

__Complete the implementation of the BetterCNN module which implements the above network in the following code block.__

In [13]:
import torch 
import torch.nn.functional as F
from torch import nn

# Model Definition
class BetterCNN(nn.Module):
    def __init__(self):
        super(BetterCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 30, (5, 5), padding=0)
        self.conv2 = nn.Conv2d(30, 15, (3, 3), padding=0)
        self.fc1 = nn.Linear(15 * 5**2, 128)
        self.fc2 = nn.Linear(128, 50)
        self.fc3 = nn.Linear(50, 10)
    
    def forward(self, x):
        # YOUR CODE HERE
        out = self.conv1(x)
        out = F.relu(out)
        out = F.max_pool2d(out, (2,2))
        out = self.conv2(out)
        out = F.relu(out)
        out = F.max_pool2d(out, (2,2))
        out = F.dropout(out, 0.2)
        out = out.view(out.shape[0], -1)
        out = self.fc1(out)
        out = F.relu(out)
        out = self.fc2(out)
        out = F.relu(out)
        out = self.fc3(out)
        return out
        
'''

The first hidden layer is a convolutional layer called a Convolution2D. The layer has 32 feature maps, which with the size of 5×5 and a rectified linear unit activation function.
Next we define a pooling layer that takes the max called MaxPooling2D. It is configured with a pool size of 2×2.
The next layer is a regularization layer using dropout called Dropout. It is configured to randomly exclude 20% of neurons in the layer in order to reduce overfitting.
Next is an operation that flattens or reshapes the tensor to a vector. It allows the output to be processed by standard fully connected layers.
Next a fully connected layer with 128 neurons and rectifier linear unit activation function.
Finally, the output layer has 10 neurons for the 10 classes.

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, (5, 5), padding=0)
        self.fc1 = nn.Linear(32 * 12**2, 128)
        self.fc2 = nn.Linear(128, 10)
            
    def forward(self, x):
        out = self.conv1(x)
        out = F.relu(out)
        out = F.max_pool2d(out, (2,2))
        out = F.dropout(out, 0.2)
        out = out.view(out.shape[0], -1)
        out = self.fc1(out)
        out = F.relu(out)
        out = self.fc2(out)
        return out
'''

'\n\nThe first hidden layer is a convolutional layer called a Convolution2D. The layer has 32 feature maps, which with the size of 5×5 and a rectified linear unit activation function.\nNext we define a pooling layer that takes the max called MaxPooling2D. It is configured with a pool size of 2×2.\nThe next layer is a regularization layer using dropout called Dropout. It is configured to randomly exclude 20% of neurons in the layer in order to reduce overfitting.\nNext is an operation that flattens or reshapes the tensor to a vector. It allows the output to be processed by standard fully connected layers.\nNext a fully connected layer with 128 neurons and rectifier linear unit activation function.\nFinally, the output layer has 10 neurons for the 10 classes.\n\nclass SimpleCNN(nn.Module):\n    def __init__(self):\n        super(SimpleCNN, self).__init__()\n        self.conv1 = nn.Conv2d(1, 32, (5, 5), padding=0)\n        self.fc1 = nn.Linear(32 * 12**2, 128)\n        self.fc2 = nn.Linea

Once you've completed the implementation, save the file and run the following code block to train and evaluate the model.

In [14]:
#reset the data loaders
torch.manual_seed(seed)
trainloader = DataLoader(trainset, batch_size=128, shuffle=True)
testloader = DataLoader(testset, batch_size=128, shuffle=True)

# build the model
model = BetterCNN()

# define the loss function and the optimiser
loss_function = nn.CrossEntropyLoss()
optimiser = optim.Adam(model.parameters())

device = "cuda:0" if torch.cuda.is_available() else "cpu"
trial = Trial(model, optimiser, loss_function, metrics=['loss', 'accuracy']).to(device)
trial.with_generators(trainloader, test_generator=testloader)
trial.run(epochs=10)
results = trial.evaluate(data_key=torchbearer.TEST_DATA)
print(results)

assert results['test_acc'] > 0.99


tensor([[-0.0565,  0.0212, -0.0290,  ..., -0.1092, -0.1373,  0.1049],
        [-0.0470,  0.0353, -0.0351,  ..., -0.0894, -0.1206,  0.1036],
        [-0.0427,  0.0299, -0.0086,  ..., -0.1085, -0.1178,  0.0985],
        ...,
        [-0.0616,  0.0234, -0.0187,  ..., -0.0976, -0.1252,  0.1134],
        [-0.0407,  0.0283, -0.0446,  ..., -0.0869, -0.1278,  0.1033],
        [-0.0624,  0.0217, -0.0130,  ..., -0.0929, -0.0968,  0.0940]],
       device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[-0.0571,  0.0107, -0.0018,  ..., -0.1065, -0.1077,  0.0895],
        [-0.0536,  0.0205,  0.0056,  ..., -0.1098, -0.1133,  0.0753],
        [-0.0650,  0.0059,  0.0190,  ..., -0.1114, -0.0937,  0.0739],
        ...,
        [-0.0482,  0.0121,  0.0108,  ..., -0.1241, -0.1066,  0.0900],
        [-0.0601,  0.0081, -0.0031,  ..., -0.1022, -0.0904,  0.0877],
        [-0.0548,  0.0083,  0.0049,  ..., -0.1052, -0.1033,  0.0947]],
       device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[-0.0741,  0.0030,  0.0098

       device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[ 0.2548, -0.0910, -0.2217,  ...,  0.1756,  0.3535, -0.4062],
        [ 0.5800, -0.5952, -0.4002,  ...,  0.0291,  0.3845, -0.3105],
        [-0.3521,  0.6818,  0.1256,  ..., -0.0686,  0.6550, -0.3646],
        ...,
        [ 0.0998, -0.0293,  0.1511,  ..., -0.2104,  0.5923, -0.4526],
        [ 1.1792, -0.7373, -0.0082,  ..., -0.1688,  0.3481, -0.4411],
        [ 1.5716, -1.0538, -0.1174,  ..., -0.2012,  0.2480, -0.5631]],
       device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[ 0.2021, -0.2127,  0.0640,  ..., -0.2177,  0.2556, -0.2761],
        [-0.6150,  0.8268,  0.0467,  ..., -0.1533,  0.7734, -0.3605],
        [ 1.1518, -1.2487, -0.1763,  ...,  0.1095,  0.0347, -0.2898],
        ...,
        [ 0.2512, -0.5632, -0.6529,  ...,  0.8503,  0.4417, -0.1685],
        [ 0.5588, -0.7485, -0.1926,  ..., -0.0276,  0.2395, -0.1315],
        [ 1.4994, -1.1476, -0.1145,  ..., -0.2017,  0.1896, -0.3678]],
       device='cuda:0', grad_fn=<A

KeyboardInterrupt: 

If correctly implemented you should see this slightly larger model achieves the respectable classification accuracy of 99.13%.

## Saving models

Being able to train a model is fine, but in practice once we've trained the model we probably want to save the result so we can reuse it at a later time. PyTorch makes saving the model easy using the `torch.save(state, filepath)` function. This will save the weights of the model so they can be loaded into a new instance at a later point. 

__Run the following code to save the weights for use in the next part of the lab.__

In [9]:
#save the trained model weights
torch.save(model.state_dict(), "./bettercnn.weights")

__If you are running on Colab, run the following to download the weights to the local machine:__

In [ ]:
from google.colab import files
files.download('bettercnn.weights')

In [6]:
# load data
transform = transforms.Compose([
    transforms.ToTensor()  # convert to tensor
])
trainset = MNIST(".", train=True, download=True, transform=transform)
testset = MNIST(".", train=False, download=True, transform=transform)

trainloader = DataLoader(trainset, batch_size=128, shuffle=True)
testloader = DataLoader(testset, batch_size=128, shuffle=True)

In [12]:
print(trainset[0])

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000