In [1]:
import torch
torch.cuda.is_available()
# https://colab.research.google.com/gist/jonhare/d98813b2224dddbb234d2031510878e1/notebook.ipynb#scrollTo=0KtFLvvUI5I3

True

In [11]:
import torch

# create an empty floating point tensor
x = torch.empty(1, 3)
print(x)

# Creation of default floating point tensor (float32) filled with ones
y = torch.ones(2,5)

# Creation of Integer tensor from existing data; The bad way (because you've _explicitly_ created a CPU-backed Tensor)
zbad = torch.IntTensor([[1, 2, 3], [4, 5, 6]])
print(zbad)

# Creation of Integer tensor from existing data; The good way (this way allows you to specify device=... so it could be backed by the GPU)
z = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
print(z)

tensor([[ 0.0000e+00,  4.4766e+00, -1.0321e+15]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
print(x.size())
print(x.shape) #usually used in preference to size()

print(z.type()) # the underlying class; this will be dependent on the backing device (so there are different FloatTensor implementations for different devices)
print(z.device) # the actual backing device (which isn't just cpu/gpu, but could tell you which gpu...)

torch.Size([1, 3])
torch.Size([1, 3])
torch.FloatTensor
cpu


In [14]:
x[0,0] = 0 #setting a specific value
print(x)

x[0,1:2] = 0 #setting a range of values (the slice operator : works just like in numpy)
print(x)

# Setting all  the values. Note all in-place operations are suffixed with an underscore
x.fill_(1.125)
print(x)

tensor([[0.0000, 1.1250, 1.1250]])
tensor([[0.0000, 0.0000, 1.1250]])
tensor([[1.1250, 1.1250, 1.1250]])


In [15]:
print(x.mean())
print(x.std())

tensor(1.1250)
tensor(0.)


In [21]:
print(x.sum().shape)
print(x.sum())
## 0d tensor can be converted back to a Python scalar with item()
print(x.sum().item())

torch.Size([])
tensor(3.3750)
3.375


In [25]:
print(z.numpy())

print(z.cpu().numpy())
print(z[0,0].item())

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
1.0


In [27]:
x = torch.tensor([ 10., 20., 30.])
y = torch.tensor([ 11., 21., 31.])

print(x + y) #Tensor-Tensor addition (element-wise addition)
print(x - y) #Tensor-Tensor subtraction (element-wise subtraction)
print(x * y) #Hadamard product of two tensors
print(x / y) #Hadamard division of two tensors

print("_______")

print(x**2) #raising to a power
print(torch.sin(x)) #applying sin element-wise
print(x == 10) #element-wise boolean tests
print(x <= 20) #element-wise boolean tests
print((x <= 20) & (x==10)) #element-wise logical `and`

tensor([21., 41., 61.])
tensor([-1., -1., -1.])
tensor([110., 420., 930.])
tensor([0.9091, 0.9524, 0.9677])
_______
tensor([100., 400., 900.])
tensor([-0.5440,  0.9129, -0.9880])
tensor([ True, False, False])
tensor([ True,  True, False])
tensor([ True, False, False])


In [29]:
x = torch.tensor([ 10., 20., 30.]) #x is a 1d tensor
m = torch.tensor([[ 0., 0., 1. ],
                  [ 0., 2., 0. ],
                  [ 3., 0., 0. ]]) #m is a 2d tensor

try:
    print(torch.mm(m,x)) #torch.mm performs matrix-matrix multiplication; this will fail because .mm doesn't support broadcasting and the inputs have differing tensor order
except Exception as e:
    print("Error: " + str(e))
print(torch.matmul(m,x)) #torch.matmul performs matrix-matrix multiplication with broadcasting; it will automatically convert x to a 2d tensor so the multiplication can be performed
print(m @ x) #ampersand is convienent short-hand notation for matmul


Error: Dimension out of range (expected to be in range of [-1, 0], but got 1)
tensor([30., 40., 30.])
tensor([30., 40., 30.])


In [30]:
#Unsqueezing tensors - this is something you'll probably see a lot; unsqueezing adds another dimensio

x = torch.tensor([ 10., 20., 30.])
print(x.shape)
x.unsqueeze_(-1) #in-place unsqueeze, adding the new dimension in the last position (so we create a _column_ vector)
print(x.shape)

print(x.t().shape) #note .t() transposes a tensor

print(torch.mm(m,x)) #  the previous .mm that failed because of mismatched sizes will now work

torch.Size([3])
torch.Size([3, 1])
torch.Size([1, 3])
tensor([[30.],
        [40.],
        [30.]])


In [31]:
x2 = x.reshape(3) # back to where we started!
print(x2)

tensor([10., 20., 30.])
